version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: aaa-mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped